#!/usr/bin/env python3
"""Embed the shared feedback widget in the standalone native/cloud explorers."""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
START = '<!-- shared feedback widget: generated by scripts/sync_feedback.py -->'
END = '<!-- end shared feedback widget -->'
FILES = ['cloudflare/utxo-video-worker/static/explorer.html', 'src/cpp/app/explorer_ui/explorer.html']

def sync(html):
    widget = START + '\n<script>\n' + (ROOT/'site/assets/feedback.js').read_text() + '</script>\n' + END
    if START in html:
        start = html.index(START)
        end = html.index(END, start) + len(END)
        return html[:start] + widget + html[end:]
    return html.replace('</body>', widget + '\n</body>')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name in FILES:
        path = ROOT/name
        old = path.read_text()
        new = sync(old)
        if args.check:
            if old != new: raise SystemExit(f'{name}: run python3 scripts/sync_feedback.py')
        else: path.write_text(new)
    print('Shared feedback widget: both explorers match.')
